# This is a basic workflow to help you get started with Actions

name: CI

env:
  LANG: "zh_CN.UTF-8"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - "latest"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Dress
        uses: actions/checkout@master
        with:
          repository: komeiji-satori/Dress
      - name: Index list
        run: git ls-tree -r --name-only master
      - name: pwd
        run: pwd
      - name: release
        uses: softprops/action-gh-release@v1
        
